name: Psalm Static analysis

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Psalm – Static Analysis for PHP
        uses: psalm/psalm-github-actions@2.3.0
        with:
            security_analysis: true
            args: --shepherd --threads=2 --no-cache